#database
spring:
  datasource:
    url: jdbc:mysql://192.168.10.203:3306/ecredentials_invoice?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 100
        min-idle: 1
    timeout: 10000ms
  rabbitmq:
    host: 127.0.0.1 #192.168.10.203
    port: 5672
    username: springcloud #rabbitadmin
    password: springcloud #123456
    virtual-host: /
    publisher-confirms: true  #  消息发送到交换机确认机制,是否确认回调
    publisher-returns: true