#database
spring:
  datasource:
    url: jdbc:mysql://192.168.20.65:3306/deliver?characterEncoding=utf8&useSSL=false
    username: myuser
    password: mypwd
    driverClassName: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
#rabbitmq
  rabbitmq:
    host: 192.168.10.203
    username: rabbitadmin
    password: 123456
    virtual-host: /
    port: 5672
    publisher-confirms: false  #  消息发送到交换机确认机制,是否确认回调
    publisher-returns: true
