spring:
  http:
    multipart:
      max-file-size: 2000Mb      # Max file size，默认1M
      max-request-size: 2500Mb   # Max request size，默认10M
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  cloud:
    loadbalancer:
      retry:
        enabled: true

  # DATASOURCE
  datasource:
    # druid 数据连接池
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

# 组件配置
component:
  # 启用数据库
  database:
    enabled: true

  # sql日志
  log4jdbc:
    enabled: true

  # 线程池
  threadpooltask:
    enabled: false

  # 缓存
  cache:
    # 启用
    enabled: true
    # Redis 作为缓存
    redis:
      enabled: true
      # 默认的超时时间  秒  1day
      default-ttl: 86400
      # 设置不同缓存的过期时间 name 对应 @Cacheable value 或者 @CacheConfig cacheNames
      cache-name-config:
        - name: user
          ttl: 3600

  # jwt token
  jwt:
    enabled: false
    config:
      secret: 6RnNZ$U%
      expiration: 604800

  # 启用cors 跨域请求
  cors:
    enabled: false
    config:
      eleccred:
        mapping: /**
        allowCredentials: true
        allowedOrigins: "*"
        allowedMethods: POST,GET,DELETE,PUT
        allowedHeaders: "*"

  # 启用CSRF防御 使用JWT后可以停用
  csrf:
    enabled: false
    patterns: /**

  # 启用XSS防御
  xss:
    enabled: false
    patterns: /*

  # 启用访问 log日志
  weblog:
    enabled: false

  # 启用shiro
  shiro:
    enabled: false

  # 启用quartz
  quartz:
    enabled: false

  # 启用schedule
  schedule:
    enabled: false

  # idworker
  idworker:
    maxCount: 1000
    type: uuid
    

ams:
  oauth2:
    encrypt:
      key-store:
        location: ams.jks
        secret: 97tKGuMKwhixD4hBbMmIbA==
        alias: ams
    #clients:
    #  - clientId: ams
    #    clientSecret: ams
    #    scope: ams
    resource-id: ams

security:
  # websecurity 忽略访问控制  
  ignore:
    urls:
      - /authentication/**
      - /**/*.css
      - /social
      - /signin
      - /signup
      - /actuator
      - /actuator/**
      - /info
      - /health
      - /metrics/**
      - /loggers/**
      - /mobile/token
      - /swagger-resources/**
      - /**/swagger-resources/**
      - /swagger-ui.html
      - /**/swagger-ui.html
      - /*/v2/api-docs
      - /**/v2/api-docs
      - /swagger/api-docs
      - /webjars/**
      - /webjars**
      - /**/webjars/**
      - /static/**
      - /**/static/**